local o = vim.o
local opt = vim.opt
local g = vim.g

o.number = true
o.relativenumber = true
o.tabstop = 4
o.shiftwidth = 4
o.softtabstop = 4
o.signcolumn = "number"
o.cursorlineopt = "both"
o.autoread = true
opt.cursorline = true
opt.autoindent = true
opt.smartindent = true
opt.clipboard = "unnamedplus"
opt.swapfile = false
opt.undodir = vim.fn.stdpath("data") .. "/undo"
opt.undofile = true
opt.guicursor = ""
opt.title = true
g.netrw_banner = false
g.netrw_liststyle = 3
g.mapleader = " "
g.maplocalleader = "\\"
